org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
minecraft_version=1.21.5
neoform_version=1.21.5-20250325.162830

# NeoForge
neoforge_version=21.5.2-beta

# Fabric
fabric_loader_version=0.16.10
fabric_api_version=0.119.5+1.21.5

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=command_structures
mod_name=Command Structures
mod_version=4.4.4
mod_description=Spawn structures by command.
sources_url=https://github.com/TelepathicGrunt/CommandStructures
issues_url=https://github.com/TelepathicGrunt/CommandStructures/issues
license_url=https://github.com/TelepathicGrunt/CommandStructures/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/565119

# Publishing
mod_group_id=com.telepathicgrunt.command_structures
curseforge_id=565119
modrinth_id=WEfvvlnl