org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=26.1
neoform_version=26.1-1

# NeoForge
neoforge_version=26.1.0.1-beta

# Fabric
fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=command_structures
mod_name=Command Structures
mod_version=4.4.5
mod_description=Spawn structures by command.
sources_url=https://github.com/TelepathicGrunt/CommandStructures
issues_url=https://github.com/TelepathicGrunt/CommandStructures/issues
license_url=https://github.com/TelepathicGrunt/CommandStructures/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/projects/565119

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id=565119
modrinth_id=WEfvvlnl

# Helper Dependencies that only exist at runtime
wits_neoforge=1.4.1+26.1-neoforge
wits_fabric=1.4.1+26.1-fabric