modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="MIT License"

[[mods]] #mandatory
modId="command_structures" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Command Structure Mod" #mandatory
authors="TelepathicGrunt" #optional
description='''
Spawn structures by command
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.command_structures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"